routes/web.php
	<?php

	/*
	|--------------------------------------------------------------------------
	| Web Routes
	|--------------------------------------------------------------------------
	|
	| Here is where you can register web routes for your application. These
	| routes are loaded by the RouteServiceProvider within a group which
	| contains the "web" middleware group. Now create something great!
	|
	*/

	Route::get('/', function () {

		return view('home', ["rutas"=>array()]);
	})->middleware('auth');

	Auth::Routes(['verify' => true]);/*registrará todas las rutas relacionadas con la autenticación,
	como inicio de sesión, registro y restablecimiento de contraseña. La */

	Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
	{

			// rutas globales
		Route::middleware(['web','auth'])->group(function (){
			Route::get('/perfil' , 'PerfilesController@index');

		});

		Route::get('Programmer/Routes','ProgrammerController@routes');
		Route::get('Programmer/getRoutes/{id}','ProgrammerController@getRoutes');
		Route::get('Programmer/saveRoutes','ProgrammerController@saveRoutes');
		 //routes permisos
		Route::get('permisos','PermisosController@index');
		Route::post('tablapermisos','PermisosController@tablapermisos');
		Route::post('agregarpermisos','PermisosController@agregarpermisos');
		Route::post('guardarpermisos','PermisosController@guardarActualizar');
		//rutas agregadas de Hoteles

		Route::resource('hoteles','HotelesController');
		Route::post('tablaHoteles','HotelesController@tablaHoteles');
		Route::post('agregarHoteles','HotelesController@agregarHoteles');
		Route::post('guardarHoteles','HotelesController@guardarActualizar');
		Route::post('agregareditar','HotelesController@agregareditar');
		Route::get ('verusuarios','HotelesController@verusuarios');
		Route::post('fotos','HotelesController@fotos');

		// controlador de guardar Modulos
		Route::resource('categorias','CategoriasController');
		Route::post('tablacategorias','CategoriasController@tablacategorias');
		Route::post('agregarcategorias','CategoriasController@agregarCategorias');
		Route::post('guardarcategorias','CategoriasController@guardarActualizar');
		Route::get('exportar', 'CategoriasController@export');
		Route::post('accionescategorias','CategoriasController@accionescategorias');

		// controlador de cuenta
		Route::resource('cuenta','CuentaController');
   		// controlador de sitios
		Route::resource('sitios','SitiosController');
		Route::get('sitios.index','SitiosController@Index');
		Route::post('tablasitios' ,'SitiosController@Tablasitios');
		Route::post('agregarsitios','SitiosController@Agregarsitios');
		Route::post('guardarsitios','SitiosController@Guardaractualizar');
		Route::post('agregareditar','SitiosController@Agregareditar');
		Route::get('exportar', 'SitiosController@export');

		// rutas de perfiles
		Route::get('acciones','PerfilesController@acciones');
		Route::resource('perfiles','PerfilesController');
		Route::post('tablaperfiles','PerfilesController@Tablaperfiles');
		Route::post('agregarperfiles','PerfilesController@Agregarperfiles');
		Route::post('guardarperfiles','PerfilesController@Guardaractualizar');
		Route::post('agregar_ruta_perfil','PerfilesController@agregar_ruta_perfil');
		Route::get('agregaraccion','PerfilesController@agregaracciones');
		Route::post('traerpermisos_perfil','PerfilesController@traerpermisos_perfil');

		// rutas de usuarios

		Route::get('usuarios','UsuariosController@index');
		Route::get('usuarios.index','UsuariosController@index');
		Route::get('/departamento/{id}','UsuariosController@getPuestos');
		Route::post('tablausuarios','UsuariosController@tablausuarios');
		Route::post('agregarusuarios','UsuariosController@Agregarusuarios');
		Route::post('guardarusuarios','UsuariosController@Guardaractualizar');

		//rutas de usuarios de hoteles
		Route::get('hotelusuarios','UsuariosHotelController@index');
		Route::post('Tablausuarioshotel','UsuariosHotelController@Tablausuarioshotel');
		Route::post('Agregarusuarioshotel','UsuariosHotelController@Agregarusuarios');
		Route::post('Guardarusuarioshotel','UsuariosHotelController@Guardaractualizar');


		//Rutas de departamentos
		Route::resource('Departamentos','DepartamentosController');
		Route::get('Departamentos','DepartamentosController@index');
		Route::post('Tabladepartamentos','DepartamentosController@Tabladepartamentos');
		Route::post('Agregardepartamentos','DepartamentosController@Agregardepartamentos');
		Route::post('Guardardepartamentos','DepartamentosController@Guardaractualizar');

		//ruta de puestos

		Route::get('puestos','PuestosController@index');
		Route::post('Tablapuestos','PuestosController@tablaPuestos');
		Route::post('Agregarpuestos','PuestosController@agregarPuestos');
		Route::post('Guardarpuestos','PuestosController@Guardaractualizar');

		//ruta de corporativo
		Route::get('corporativo','CorporativosController@index');
		Route::post('tablaCorporativos','CorporativosController@tablaCorporativos');
		Route::post('agregarCorporativos','CorporativosController@agregarCorporativos');
		Route::post('guardarCorporativos','CorporativosController@guardarActualizar');

		//ruta de Empresas
		Route::resource('empresas','EmpresasController');
		Route::get('girosBysegmentos/{id}','EmpresasController@bysegmento');
		Route::post('tablaempresas','EmpresasController@Tablaempresas');
		Route::post('Agregarempresas','EmpresasController@Agregarempresas');
		Route::post('Guardarempresas','EmpresasController@GuardarActualizar');


		//rutasoist
		Route::get('rutasmostrar','PermisosController@rutas');

		//contactos
		Route::resource('contactos','ContactosController');
		Route::get('contactos','ContactosController@index');
		Route::post('Tablacontactos','ContactosController@tablacontactos');
		Route::post('Agregarcontactos','ContactosController@Agregarcontactos');
		Route::post('Guardarcontactos','ContactosController@GuardarActualizar');
		//rutas de segmentos
		Route::resource('segmentos','SegmentosController');
		Route::get('segmentos','SegmentosController@index');
		Route::post('Tablasegmentacion','SegmentosController@Tablasegmentacion');
		Route::post('Agregarsegmentacion','SegmentosController@Agregarsegmentacion');
		Route::post('GuardarSegmentacion','SegmentosController@GuardarActualizar');

		//rutas de giros de la empresa

		Route::get('giros','GirosController@index');
		Route::post('Tablagiros','GirosController@Tablagiros');
		Route::post('Agregargiros','GirosController@Agregargiros');
		Route::post('Guardargiros','GirosController@GuardarActualizar');

	//rutas titulos
		Route::get('titulos','TitulosController@index');
		Route::post('Tablatitulos','TitulosController@Tablatitulos');
		Route::post('Agregartitulos','TitulosController@AgregarTitulos');
		Route::post('Guardartitulos','TitulosController@GuardarActualizar');

	//niveles

		Route::get('niveles','NivelesController@index');
		Route::post('Tablaniveles','NivelesController@Tablaniveles');
		Route::post('Agregarniveles','NivelesController@Agregarniveles');
		Route::post('Guardarniveles','NivelesController@Guardaractualizar');

   //rutas agenda

		Route::get('agenda','AgendasController@index');
		Route::post('Tablaagenda','AgendasController@Tablaagenda');
		Route::post('Agregaragenda','AgendasController@Agregaragenda');
		Route::post('Guardaragenda','AgendasController@Guardaractualizar');





	}

app/Http/Controllers/HotelesController.php
<?php

namespace App\Http\Controllers;
use  Illuminate\Http\Request;
use Illuminate\Foundation\Http\FormRequest;
use App\Http\Requests\HotelRequest;
use App\Hotel;
use DB;



    class Hotelescontroller extends Controller
    


{
       
    public function index()
            {
                $hoteles =Hotel::all();
                return view('hoteles.index',compact('hoteles'));
            }


            //Metodo de tablaHoteles
            public function tablaHoteles( Request $request)
            {
                $hoteles=Hotel::all(); 
                return view('hoteles.tablaHoteles',compact('hoteles'));
             }

            // Metodo de agregarHoteles
            public function agregarHoteles(Request $request)
            {

            //$id = $request->get("id");

        //$hoteles=Hotel::where($id); 
            $hoteles=Hotel::find($request);
            return view('hoteles.agregarHoteles',['hoteles'=>$hoteles]);
        }

    public function guardarActualizar(HotelRequest $request)
        {
            //return $request->all();
      
  
            $arreglo = array();
            foreach($request as $k=>$v) $arreglo[$k] = $v;
            $id = $request->id;
            unset($request->id);

            $retornar = ($id)? self::actualizar($request,$id) : self::agregar($request);
            
            return ($retornar)? "success" : "error";
            

        
        }

        private function agregar($data){

    //         $arreglo = array();
    //         foreach($data as $k=>$v) $arreglo[$k] = $v;
    //    //Hotel::create($arreglo);
     

         $affected = DB::table('hotel')->insert([
                'nombrehotel'=>$data['nombrehotel'],
                'codigohotel'=>$data['codigohotel'],
                'direccioncomercial'=>$data['direccioncomercial'],
                'codigohotel'=>$data['codigohotel'],
                'colonia'=>$data['colonia'],
                'cp'=>$data['cp'],
                'idciudad'=> $data['idciudad'],
                'idestado'=> $data['idestado'],
                'idpais'=>$data['idpais'],
                'razonsocial'=>$data['razonsocial'],
                'calleynumero'=>$data['calleynumero'],
                'idciudadfiscal'=>$data['idciudadfiscal'],
                'idestadofiscal'=>$data['idestadofiscal'],
                'idpaisfiscal'=>$data['idpaisfiscal'],
                'telefonodirecto'=>$data['telefonodirecto'],
                'telefono2'=>$data['telefono2'],
                'fax'=>$data['fax'],
                'web'=>$data['web'],
                'idmarca'=>$data['idmarca'],
                'idgrupohotelero'=>$data['idgrupohotelero'],
                'logohotel'=>$data['logohotel'],
                'principalcontacto'=>$data['principalcontacto'],
                'idpuesto'=>$data['idpuesto'],
                'notas'=>$data['notas'],
                'nodehabitaciones'=>$data['nodehabitaciones'],
                'impuesto'=>$data['impuesto'],
                'ish'=>$data['ish'],
                'status'=>$data['status'],
                'coloniafiscal'=>$data['coloniafiscal'],
                'rfc'=>$data['rfc'],
                'latitud'=>$data['latitud'],
                'longitud'=>$data['longitud'],
                'zoom'=>$data['zoom'],
                'logoconvenios'=>$data['logoconvenios'],
                'idcorporativo'=>$data['idcorporativo'],
                'incContrato'=>$data['incContrato'],
                'finContrato'=>$data['finContrato'],
                'registrado'=>$data['registrado']
            ]);

            return $affected;
         }




    
        public function actualizar($data,$id){  
              
            //$affected = DB::table('hotel')->where("id",$id)->update([
          


            $affected = DB::table('hotel')->where('id', '=', $id)->update([
                'nombrehotel'=>$data['nombrehotel'],
                'codigohotel'=>$data['codigohotel'],
                'direccioncomercial'=>$data['direccioncomercial'],
                'colonia'=>$data['colonia'],
                'cp'=>$data['cp'],
                'idciudad'=> $data['idciudad'],
                'idestado'=> $data['idestado'],
                'idpais'=>$data['idpais'],
                'razonsocial'=>$data['razonsocial'],
                'calleynumero'=>$data['calleynumero'],
                'idciudadfiscal'=>$data['idciudadfiscal'],
                'idestadofiscal'=>$data['idestadofiscal'],
                'idpaisfiscal'=>$data['idpaisfiscal'],
                'telefonodirecto'=>$data['telefonodirecto'],
                'telefono2'=>$data['telefono2'],
                'fax'=>$data['fax'],
                'web'=>$data['web'],
                'idmarca'=>$data['idmarca'],
                'idgrupohotelero'=>$data['idgrupohotelero'],
                'logohotel'=>$data['logotel'],
                'principalcontacto'=>$data['principalcontacto'],
                'idpuesto'=>$data['idpuesto'],
                'notas'=>$data['notas'],
                'nodehabitaciones'=>$data['nodehabitaciones'],
                'impuesto'=>$data['impuesto'],
                'ish'=>$data['ish'],
                'status'=>$data['status'],
                'coloniafiscal'=>$data['coloniafiscal'],
                'rfc'=>$data['rfc'],
                'latitud'=>$data['latitud'],
                'longitud'=>$data['longitud'],
                'zoom'=>$data['zoom'],
                'logoconvenios'=>$data['logoconvenios'],
                'idcorporativo'=>$data['idcorporativo'],
                'incContrato'=>$data['incContrato'],
                'finContrato'=>$data['finContrato'],
                'registrado'=>$data['registrado'], 

                
        ]);

        return $affected;



        }

   
    public function destroy($id)
        {
            $hotel = Hotel::find($id);
            $hotel->delete();
            return redirect('/hoteles')->with('success', 'Stock has been deleted Successfully');
        }
    //metedo de verusuarios para verlos en un modal
    public function verUsuarios(){

        return view('hoteles.modal');
    } 
       //metodo de guardar y actualizar de cotizaciones
      public function guardarActualizarCotizacion(Request $request)
        {
            //return $request->all();
      
  
            $arreglo = array();
            foreach($request as $k=>$v) $arreglo[$k] = $v;
            $id = $request->id;
            unset($request->id);

            $retornar = ($id)? self::actualizar($request,$id) : self::agregar($request);
            
            return ($retornar)? "success" : "error";
            

        
        }  


    public function actualizarCotizacion($data ,$id){

        $affected=BD::table('hotel')->insert([

      'incContrato'=>$data['incContrato'],
      'plan'=>$data['plan'],
      'finContrato'=>$data['finContrato'],
      'costoxmes'=>$data['costoxmes'],
      'descuento'=>$data['descuento'],
      'total'=>$data['total'],
      'apertura'=>$data['apertura'],
      'mantenimiento'=>$data['mantenimiento'],
      'costo'=>$data['costo'],
      'descuento'=>$data['descuento'],
      'costo'=>$data['descuento'],
      'total'=>$data['total'],


        ]);

       return $affected;

    } 
}

resources/views/hoteles/agregarHoteles.blade.php
<?php
//print_r($hoteles);
$count = count($hoteles);

$active = ($count)? "active" : "";

$nombrehotel = ($count)? $hoteles[0]->nombrehotel : "" ;
$direccioncomercial= ($count)? $hoteles[0]->direccioncomercial:"" ;
$colonia= ($count)? $hoteles[0]->colonia:"" ;
$codigohotel= ($count)? $hoteles[0]->codigohotel:"" ;
$cp= ($count)? $hoteles[0]->cp: "" ;
$pais= ($count)? $hoteles[0]->pais: "" ;
$estado= ($count)? $hoteles[0]->estado: "" ;
$ciudad=($count)? $hoteles[0]->ciudad: "";
$idpaisfiscal=($count)? $hoteles[0]->idpaisfiscal: "";
$idestadofiscal=($count)? $hoteles[0]->idestadofiscal: "";
$idciudadfiscal=($count)? $hoteles[0]->idciudadfiscal: "";
$calleynumero=($count)? $hoteles[0]->calleynumero:  "";
$telefonodirecto=($count)? $hoteles[0]->telefonodirecto:  "";
$telefono2=($count)? $hoteles[0]->telefono2:  "";

$rfc=($count)? $hoteles[0]->rfc:  "";
$cp=($count)? $hoteles[0]->cp:  "";
$razonsocial=($count)? $hoteles[0]->razonsocial:  "";
$web=($count)? $hoteles[0]->web:  "";
$principalcontacto=($count)? $hoteles[0]->principalcontacto: "";
$incContrato=($count)? $hoteles[0]->incContrato: "";
$finContrato=($count)?$hoteles[0]->finContrato:"";
$notas=($count)?$hoteles[0]->notas:"";
$logohotel=($count)?$hoteles[0]->logohotel:"";
$idcorporativo=($count)?$hoteles[0]->idcorporativo:"";


?>
<!--Modal de editar-->
<div class="modal-content">
   <h4>Grupo EnlaceForte</h4>
   <hr>
   <meta name = "viewport" content = "width = device-width, initial-scale = 1">      
   <script type = "text/javascript" src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>           
   <script src = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>  
   <div class = "row">
      <div class = "col s12">
        <ul class = "tabs" bgcolor="#00AAE4">
         <li class = "tab col s3"><a  class = "active" href = "#hotel">Hotel</a></li>
         <li class = "tab col s3"><a  href = "#detalle">Detalle</a></li>
         <li class = "tab col s3"><a href = "#contrato">Plan de Contrato</a></li>
         <li class="  tab col s3"><a href="#contacto">Contacto</a></li>
     </ul>
 </div>
 <div id = "contrato" class = "col s12">Sent</div>
</div> 


<form id='datosHotel' class="formValidate" id="formValidate" method="get">
    <br>

    
    @csrf
    <div class="row" id="hotel">

        <div class="input-field col s6">
            <input id="icon_prefix1" type="text" id="nombre" class="validate" name="nombrehotel" 
            value='{{$nombrehotel}}' required aria-required="true" placeholder="nombrehotel" required autocomplete="nombrehotel">
            <label for="icon_prefix1" class="center-align {{$active}}"><h6>{{ __('NombreHotel') }}</h6></label>
            <p class='errornombrehotel text-center alert alert-danger hidden'></p>
        </div>

        <div class="input-field col s6">
            <input id="icon_prefix3" type="text" id="direccioncomercial" class="validate" name="direccioncomercial"
            value="{{$direccioncomercial}}" placeholder="direccioncomercial" required autocomplete="direccioncomercial">
            <label for="icon_prefix3" class="center-align {{$active}}"><h6>{{ __('Direccion Comercial') }}</h6></label>
        </div>


        <div class="input-field col s6">        
            <input id="icon_prefix4" type="text" id="colonia" class="validate" name="colonia"
            value="{{$colonia}}" placeholder="colonia" required autocomplete="colonia" >
            <label for="icon_prefix4" class="center-align {{$active}}"><h6>{{ __('Colonia') }}</h6></label>
        </div>


        <div class="input-field col s6">
            <input id="icon_prefix5" type="text" id="codigohotel"  class="validate" name="codigohotel" required autocomplete="codigohotel" 
            value="{{$codigohotel}}" placeholder="codigohotel">
            <label for="icon_prefix5" class="center-align {{$active}}"><h6>{{ __('Codigo H') }}</h6></label>
        </div>
        

        <div class="col s6">
            <label for="pais">{{$pais}}</label>
            <select class="error browser-default" id="crole" name="crole" data-error=".errorTxt6">
                <option value="" disabled selected>{{ __('seleccione Pais') }}</option>
                <option value="1">{{ __('México') }}</option>
                <option value="2">España</option>
                <option value="3">Argentina</option>
            </select>
            <div class="input-field">
                <div class="errorTxt6"></div>
            </div>
        </div>

        <div class="col s6">
            <label for="estado">{{$estado}}</label>
            <select class="error browser-default" id="crole" name="crole" data-error=".errorTxt6">
                <option value="" disabled selected>seleccione Estado</option>
                <option value="1">Nuevo León</option>
                <option value="2">San Luis Potosí</option>
                <option value="3">Tamaulipas</option>
            </select>
            <div class="input-field">
                <div class="errorTxt6"></div>
            </div>
        </div>

        <div class="col s6">
            <label for="ciudad">{{$ciudad}}</label>
            <select class="error browser-default" id="crole" name="crole" data-error=".errorTxt6">
                <option value="" disabled selected>seleccione ciudad</option>
                <option value="1">Monterrey</option>
                <option value="2">San Luis Potosí</option>
                <option value="3">Tampico</option>
            </select>
            <div class="input-field">
                <div class="errorTxt6"></div>
            </div>
        </div>

        <div class="col s6">
            <label for="idpaisfiscal">{{$idpaisfiscal}}</label>
            <select class="error browser-default" id="crole" name="crole" data-error=".errorTxt6">
                <option value="" disabled selected>País Fiscal</option>
                <option value="1">México</option>
                <option value="2">España</option>
                <option value="3">Argentina</option>
            </select>
            <div class="input-field">
                <div class="errorTxt6"></div>
            </div>
        </div>


        <div class="col s6">
            <label for="idestadofiscal">{{$idestadofiscal}}</label>
            <select class="error browser-default" id="crole" name="crole" data-error=".errorTxt6">
                <option value="" disabled selected>Estado Fiscal</option>
                <option value="1">Nuevo León</option>
                <option value="2">San Luis Potosí</option>
                <option value="3">Tamaulipas</option>
            </select>
            <div class="input-field">
                <div class="errorTxt6"></div>
            </div>
        </div>


        <div class="col s6">
            <label for="idciudadfiscal">{{$idciudadfiscal}}</label>
            <select class="error browser-default" id="crole" name="crole" data-error=".errorTxt6">
                <option value="" disabled selected>Ciudad Fiscal</option>
                <option value="1">Monterrey</option>
                <option value="2">San Luis Potosí</option>
                <option value="3">Tampico</option>
            </select>
            <div class="input-field">
                <div class="errorTxt6"></div>
            </div>
        </div>

        <div class="input-field col s6">
         
            <input id="icon_prefix11" type="text" id="razonsocial" class="validate" name="razonsocial" required autocomplete="razonsocial"
            value="{{$razonsocial}}" placeholder="razonsocial">
            <label for="icon_prefix11" class="center-align"><h6>{{ __('Razón Social') }}<h6></label>
            </div>

            <div class="input-field col s6">
                <input id="icon_prefix12" type="text" id="direccion" class="validate" name="calleynumero" required autocomplete="direccion" 
                value="{{$calleynumero}}" placeholder="calle y numero">
                <label for="icon_prefix12" class="center-align"><h6>{{ __('Direccion C/N') }}</h6></label>
            </div>

            <div class="input-field col s6">
             
                <input id="icon_prefix16" type="text" id="telefonodirecto" class="validate" name="telefonodirecto" 
                value="{{$telefonodirecto}}" placeholder="Tel.Directo">
                <label for="icon_prefix16" class="center-align"><h6>{{ __('Tel.Directo') }}</h6></label>              
            </div>


            <div class="input-field col s6">
                <input id="icon_prefix13" type="text" id="telefono2" class="validate" name="telefono2" required autocomplete="telefono2" 
                value="{{$telefono2}}" placeholder="Telefono2">
                <label for="icon_prefix13" class="center-align"><h6>{{ __('Tel.Secundario') }}</h6></label>
            </div>

            

            <div class="input-field col s6">
                <input id="icon_prefix15" type="text" id="rfc" class="validate" name="rfc" required autocomplete="rfc" 
                value="{{$rfc}}" placeholder="rfc">
                <label for="icon_prefix15" class="center-align"><h6>{{ __('R.F.C') }}</h6></label>
            </div>

            <div class="input-field col s6">
                <input id="icon_prefix50" type="text" id="cp" class="validate" name="cp" required autocomplete="cp"
                value="{{$cp}}" placeholder="cp">
                <label for="icon_prefix50" class="center-align"><h6>{{ __('Codigo Postal') }}</h6></label>
            </div>

            <div class="col s6">
                <div class="switch">
                    <label>
                        Status
                        <input id="status"  type="checkbox" >
                        <span class="lever"></span>
                    </label>
                </div>
            </div>
        </div>


        <!--div del detalle-->


        
        <div class="row" id="detalle">

            <div class="input-field col s6">
                <input id="icon_prefix23" type="text" id="web" class="validate" name="web" required autocomplete="nombre" 
                value='{{$web}}' placeholder="sitio web">
                <label for="icon_prefix23" class="center-align {{$active}}"><h6>{{ __('Sitio web') }}</h6></label>
            </div>


            <div class="input-field col s6">
                <label for="idciudadfiscal">{{$idcorporativo}}</label>
                <select class="error browser-default" id="crole" name="crole" data-error=".errorTxt6">
                    <option value="" disabled selected>Corporativo</option>
                    <option value="1">Enlaceforte</option>
                    <option value="2">Holidein Inn</option>
                    <option value="3">Crown Plaza</option>
                </select>
                <div class="input-field">
                    <div class="errorTxt6"></div>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <textarea id="notas" class="materialize-textarea" data-length="120" class="validate" name="notas" 
                    value="{{$notas}}" placeholder="notas"></textarea>
                    <label for="textarea2"><h6>{{ __('Nota') }}</h6></label>
                </div>
            </div>
            
        </div>

        <!--div del contacto-->

        <div id = "contacto" class = "col s12">

            <div class="input-field col s6">
                
                <input id="icon_prefix24" type="text" id="principalcontacto" class="validate" name="principalcontacto" required autocomplete="principalcontacto"
                value="{{$principalcontacto}}" placeholder="principalcontacto">
                <label for="icon_prefix24" class="center-align {{$active}}"><h6>{{ __('Principal Contacto') }}</h6></label>
            </div>


            


            <div class="input-field col s6">
                
                <input id="icon_prefix21" type="date" id="incContrato" class="validate" name="incContrato" required autocomplete="incContrato" 
                value="{{$incContrato}}" placeholder="incContrato">
                <label for="icon_prefix21" class="center-align"><h6>{{ __('Inicio de Contrato') }}</h6></label>
                
            </div>

            <div class="input-field col s6">
                <input id="icon_prefix122" type="date" id="finContrato" class="validate" name="finContrato" required autocomplete="finContrato" 
                value="{{$finContrato}}" placeholder="finContrato">
                <label for="icon_prefix22" class="center-align">{{ __('Fin de contrato') }}</label>
            </div> 

        </div>

    </form>
</div>
<div class="modal-footer">



    <input type="submit"  class="waves-effect #00e676 green accent-3 btn-small" id='guardarHoteles' value="agregar">


    <label>
        <a href="{{url('hoteles')}}" class="waves-effect blue btn-small">Cancelar</a>
    </label>
</div>

resources/views/hoteles/delete.blade.php
<form action="{{ route('hoteles.destroy' ,$hotel->id) }}" method="POST" style="display:inline-block;">

@method('DELETE')
@csrf

<button  type ="submit" class ="waves-effect red accent-4 btn-small" onclick="return confirm()"> <i class="material-icons left">delete</i>Eliminar</button>

<script>
function myFunction() {
  alert("desea eliminar?");
}
</script>
</form>

resources/views/hoteles/index.blade.php
@extends('layouts.app')

@push('styles')
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.css">

@endpush

@push('scripts')
<script src="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.js"></script>
<script src="{{asset ('bootstrap/js/bootstrap-table.min.js') }}"></script>

@endpush

@section('container')


<div class="row">
 <div class="row">
  <div class="col s12">

    <div id="icon-prefixes" class="card card-tabs">
      <div class="card-content">

        <!-- Botton del Modal-->


        <button type="button" class="waves-effect #311b92 deep-purple darken-4 btn-small" data-toggle="modal" id="agregarhotel">
          Agregar
        </button>

        <!-- Modal Structure -->
        <div id="modal1" class="modal modal-fixed-footer">
          <div id="contenidomodal">


          </div>
          <!--Termina modal -->
          <!--Footer del modal-->

        </div>
        <!--Termina footer-->
                  <!--<div class=" row justify-content-end pb-2">
                  <a  href = "{{ route('hoteles.create')}}" class="btn-floating btn-large waves-effect  green accent-3"><i class="material-icons">person_add</i>Agregar</a>
                </div>-->


                <h4 class="card-title">{{__(' Lista de Hoteles')}}</h4>
                <!--ID DE LA TABLA -->
                <div class="col s12 " id="tabla">


                  <!-- Modal Structure -->
                  <div id="modal2" class="modal modal-fixed-footer">
                    <div id="contenidomodal">

                    </div>
                    <!--Termina modal -->
                    <!--Footer del modal-->

                  </div>
                  <!--Termina footer-->

                  <div id="modal3" class="modal modal-fixed-footer">
                    <div id="contenidomodal">

                    </div>
                    <!--Termina modal -->
                    <!--Footer del modal-->

                  </div>
                </div>






              </div></center>
            </div>
          </div>
        </div>
      </div>

      @endsection

resources/views/hoteles/search.blade.php
 
 <form method="GET" href="{{route('hoteles.index')}}" autocomplete="off" role="search">

	<div class="input-field col s6">
 	<div class="form-group">
 	<div class="input-group">
 		<i class="material-icons prefix">pageview</i>
 		<input type="text"  class="form-control" name="searchText" placeholder="Buscar..." value="{{$searchText}}">
 		</div>	
	</div>
</div>


</form>